"""Add file metadata columns

Revision ID: f337765b5444
Revises: 
Create Date: 2025-06-11 17:58:29.228397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f337765b5444'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_uploads', sa.Column('file_type', sa.String(), nullable=True))
    op.add_column('file_uploads', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('file_uploads', sa.Column('rows_count', sa.Integer(), nullable=True))
    op.add_column('file_uploads', sa.Column('columns_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_uploads', 'columns_count')
    op.drop_column('file_uploads', 'rows_count')
    op.drop_column('file_uploads', 'file_size')
    op.drop_column('file_uploads', 'file_type')
    # ### end Alembic commands ###
